# Generated by Django 6.1 on 2026-10-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpconfig',
            name='mode',
            field=models.CharField(choices=[('sms', 'SMS'), ('master', 'Master OTP')], default='sms', max_length=10),
        ),
    ]
