# Generated by Django 6.1 on 2026-09-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20),
        ),
    ]
