# Generated by Django 6.1 on 2026-09-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_rename_city_doctor_clinic_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='available_days',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
