# Generated by Django 6.1.2 on 2026-10-09 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctor_available_days_doctor_clinic_close_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='last_verification_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_doctor_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_qualification',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_remarks',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_result',
            field=models.CharField(blank=True, choices=[('found', 'Found on the register'), ('not_found', 'Not found on the register'), ('ambiguous', 'Several possible matches'), ('unavailable', 'Register unreachable')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='nmc_university',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='registration_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state_council_id',
            field=models.CharField(blank=True, choices=[('AND', 'Andhra Pradesh Medical Council'), ('ARU', 'Arunachal Pradesh Medical Council'), ('ASS', 'Assam Medical Council'), ('BIH', 'Bihar Medical Council'), ('CHA', 'Chhattisgarh Medical Council'), ('DEL', 'Delhi Medical Council'), ('GOA', 'Goa Medical Council'), ('GUJ', 'Gujarat Medical Council'), ('HAR', 'Haryana Medical Council'), ('HIM', 'Himachal Pradesh Medical Council'), ('JAM', 'Jammu & Kashmir Medical Council'), ('JHA', 'Jharkhand Medical Council'), ('KAR', 'Karnataka Medical Council'), ('MAD', 'Madhya Pradesh Medical Council'), ('MAH', 'Maharashtra Medical Council'), ('MAN', 'Manipur Medical Council'), ('MCI', 'Medical Council of India'), ('MIZ', 'Mizoram Medical Council'), ('NAG', 'Nagaland Medical Council'), ('ORI', 'Orissa Council of Medical Registration'), ('PUN', 'Punjab Medical Council'), ('RAJ', 'Rajasthan Medical Council'), ('SIK', 'Sikkim Medical Council'), ('TAM', 'Tamil Nadu Medical Council'), ('TEL', 'Telangana State Medical Council'), ('TC', 'Travancore Cochin Medical Council, Trivandrum'), ('TRI', 'Tripura State Medical Council'), ('UP', 'Uttar Pradesh Medical Council'), ('UTT', 'Uttarakhand Medical Council'), ('WES', 'West Bengal Medical Council')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='doctor',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verification_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verification_provider',
            field=models.CharField(blank=True, choices=[('nmc', 'NMC register'), ('vendor', 'Verification vendor'), ('manual', 'Checked by an admin')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('manual_review', 'Under review'), ('failed', 'Register unreachable'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('registration_number', ''), _negated=True), models.Q(('state_council_id', ''), _negated=True)), fields=('registration_number', 'state_council_id'), name='doctor_unique_registration_per_council'),
        ),
    ]
