# Generated by Django 6.1 on 2026-10-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_nmc_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='provider_attempts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='doctor',
            name='verification_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='verification_provider',
            field=models.CharField(blank=True, choices=[('nmc', 'NMC register'), ('apify', 'Apify NMC lookup'), ('decentro', 'Decentro'), ('vendor', 'Verification vendor'), ('manual', 'Checked by an admin')], default='', max_length=10),
        ),
    ]
