# Generated by Django 6.1 on 2026-08-12 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='insurance/%Y/%m/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('validated', 'Validated'), ('needs_review', 'Needs Review')], default='processing', max_length=20)),
                ('insurer', models.CharField(blank=True, max_length=150)),
                ('policy_number', models.CharField(blank=True, max_length=100)),
                ('plan_name', models.CharField(blank=True, max_length=150)),
                ('policy_type', models.CharField(blank=True, max_length=100)),
                ('sum_insured', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('coverage_start', models.DateField(blank=True, null=True)),
                ('coverage_end', models.DateField(blank=True, null=True)),
                ('room_rent_limit', models.CharField(blank=True, max_length=100)),
                ('co_payment_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='family.profile')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='insurance.insurancepolicy')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_category', models.CharField(max_length=150)),
                ('estimated_bill', models.DecimalField(decimal_places=2, max_digits=12)),
                ('eligible', models.BooleanField()),
                ('estimated_insurer_share', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estimated_out_of_pocket', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reasoning_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_estimates', to='insurance.insurancepolicy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyExclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='insurance.insurancepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicySubLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=150)),
                ('limit_text', models.CharField(max_length=255)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_limits', to='insurance.insurancepolicy')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyWaitingPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('condition', models.CharField(max_length=255)),
                ('months', models.PositiveSmallIntegerField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_periods', to='insurance.insurancepolicy')),
            ],
        ),
    ]
