# Generated by Django 6.1 on 2026-08-12 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('prescription', 'Prescription'), ('report', 'Report'), ('scan', 'Scan'), ('discharge', 'Discharge Summary'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('processed', 'Processed'), ('needs_review', 'Needs Review'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('doctor_name', models.CharField(blank=True, max_length=150)),
                ('hospital_name', models.CharField(blank=True, max_length=150)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('raw_ocr_text', models.TextField(blank=True)),
                ('structured_data', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='family.profile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='family.profile')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to='documents.document')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
