# Generated by Django 6.1 on 2026-10-03 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_stored_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='documents.document'),
        ),
    ]
