# Generated by Django 6.1 on 2026-08-12 16:31

import django.db.models.deletion
import emergency.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_token', models.CharField(default=emergency.models.generate_public_token, max_length=64, unique=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('include_blood_group', models.BooleanField(default=True)),
                ('include_allergies', models.BooleanField(default=True)),
                ('include_conditions', models.BooleanField(default=True)),
                ('include_medications', models.BooleanField(default=True)),
                ('include_emergency_contact', models.BooleanField(default=True)),
                ('include_insurance_summary', models.BooleanField(default=False)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_profile', to='family.profile')),
            ],
        ),
    ]
